import { Inter, Roboto_Mono } from 'next/font/google'
import Header from '@/components/Header'
import './globals.css'
import { Suspense } from 'react'
import Loading from './loading'
import Page from './page'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const roboto = Roboto_Mono({
    subsets: ['latin'],
})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout() {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header />
                <Suspense fallback={<Loading />}>
                    <Page />
                </Suspense>
                <Footer />
            </body>
        </html>
    )
}
